### ISSUE TITLE
I would love to see you helping build JSS

### ISSUE THREAD

**Issue by kof** [jxnblk/superstyle#1]
I realize how appealing it may sound to write another cssinjs library. Maybe I miss something, but I feel like what you want is already there. If not - I would love to hear your thoughts.

**Comment by jxnblk** [comment]
Hey, big fan of JSS. I mostly just throw these little spikes up to scratch my own itch and to experiment with what's possible – in this case using CSSOM APIs. My hope is that some of the other authors of css-in-js libraries, like glamor, styled-components, and JSS, figure out more robust solutions and better maintained projects, but hopefully little projects like this one are good food for thought.

**Comment by kof** [comment]
I see, let me know if you got time to experiment, I got a plenty of issues)
